# Generated by Django 5.2.8 on 2025-12-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_product_remove_student_email_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_city',
            field=models.CharField(max_length=101),
        ),
    ]
