# Generated by Django 5.2.8 on 2025-12-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0003_alter_customer_customer_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_segment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
