# Generated by Django 5.2.8 on 2025-12-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0004_delete_product_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.IntegerField(null=True),
        ),
    ]
