# Generated by Django 5.2.8 on 2025-12-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0005_alter_student_roll_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll_number',
            new_name='roll',
        ),
    ]
